import styles from "../styles/AboutUs/AboutUs.module.css";

function CookiesPolicy() {
    return (
        <>
        <main className="main">
            <div className="row-direction">
            <div className={styles.aboutUs}>
                <div className={styles.text}>
                <h1>Cookies Policy</h1>

                
                    <h3>Definitions and key terms</h3>
                    <p>
                    To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:
                    </p>
                    <ul>
                        <li>
                        Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.
                        </li>
                        <li>
                        Company: when this policy mentions "Company", "we", "us", or "our", it refers to Ondg Ltd, that is responsible for your information under this Cookie Policy.
                        </li>
                        <li>
                        Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Ondg and use the services.
                        </li>
                        <li>
                        Personal Data: any information that directly, indirectly, or in connection with other information ‐including a personal identification number‐ allows for the identification or identifiability of a natural person.
                        </li>
                        <li>   
                        Service: refers to the service provided by Ondg as described in the relative terms (if available) and on this platform.
                        </li>
                        <li>
                        Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                        </li>
                        <li>
                        Website: Ondg's site, which can be accessed via this URL: https://ondg.co.uk
                        </li>
                        <li>
                        You: a person or entity that is registered with Ondg to use the Services.
                        </li>
                    </ul>

                    <br />
                    <h3>Introduction</h3>
                    <p>
                    This Cookie Policy explains how Ondg uses cookies and similar technologies to recognize you when you visit our website. It explains what these technologies are and why we use them, as well as the choices for how to control them.
                    </p>

                    <br />    
                    <h3>What is a cookie?</h3>
                    <p>
                    A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, and remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.
                    </p>

                    <br />
                    <h3>Why do we use cookies?</h3>
                    <p>
                    We use first party and/or third party cookies on our website for various purposes such as:
                    </p>
                    <p>
                    To facilitate the operation and functionality of our website;
                    To improve your experience of our website and make navigating around them quicker and easier;
                    To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;
                    To analyse how our website is used and how best we can customise it;
                    To identify future prospects and personalise marketing and sales interactions with it;
                    To facilitate the tailoring of online advertising to your interests.
                    </p>

                    <br />
                   <h3>What type of cookies does Ondg use?</h3>
                    <br />
                    <p> 
                    Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you're visiting are called "first party cookies".
                    </p>
                    <br />

                    <p>
                    Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website. We use the following types of cookies in our website:
                    </p>

                    <br />
                    <h3>Essential Cookies</h3>
                    <p>
                    We use essential cookies to make our website work. The cookies necessary for Ondg to work allow us to:
                    </p>
                    <p>
                    add items to your basket and create an order;
                    check your order status;
                    enable customer service agents to chat with you;
                    keep records of your consent to our use of cookies.
                    </p>
                    <p>
                    Without these cookies you might not be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.
                    </p>

                    <br />
                    <h3>Functional Cookies</h3>
                    <p>
                    These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable.
                    </p>
                    <br />

                    <h3>Analytics Cookies</h3>
                    <br />
                    <p>
                    These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customise our website for you. We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at: https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our Websites by visiting: https://tools.google.com/dlpage/gaoptout.
                    </p>
                    <br />

                    <h3>How you can manage cookies?</h3>
                    <br />
                    <p>
                    Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalised to you. It may also stop you from saving customised settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.
                    </p>
                    <br />

                    <h3>Blocking and disabling cookies and similar technologies</h3>
                    <br />  
                    <p>
                    Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilise all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
                    </p>

                    <br />
                    <h3>Changes To Our Cookie Policy</h3>
                    <br />
                    <p>
                    We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.
                    </p>
                    <br />

                    <h3>Your Consent</h3>
                    <br />
                    <p>
                    By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.
                    </p>
                    <br />

                    <h3>Contact Us</h3>
                    <br />
                    <p>
                    Don't hesitate to contact us if you have any questions regarding our Cookie Policy. Via Email: support@ondg.co.uk
                    </p>
                    <br />
                    <p>
                    Last updated: 1st February 2023.
                    </p>

                    </div>
                </div>
            </div>
        </main>
        </>    
    );
}

export default CookiesPolicy;